name: Deploy to Azure Container Registry

on:
  push:
    branches:
      - main  # Ejecuta el flujo de trabajo al hacer push en la rama principal

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. Clona el repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configura Docker
    - name: Log in to Azure Container Registry
      run: echo "${{ secrets.AZURE_REGISTRY_PASSWORD }}" | docker login ${{ secrets.AZURE_REGISTRY_NAME }} -u ${{ secrets.AZURE_REGISTRY_USERNAME }} --password-stdin

    # 3. Construye y sube la imagen
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.AZURE_REGISTRY_NAME }}/bikework-api-maintenance:latest -f bikework_api_maintenance/Dockerfile .
        docker push ${{ secrets.AZURE_REGISTRY_NAME }}/bikework-api-maintenance:latest